# Copyright (c) 2024-2025, AutoMoMa Authors. All rights reserved.
# SPDX-License-Identifier: MIT
"""Environment setup utilities for AutoMoMa."""

import os
import shutil
import sys
from pathlib import Path


def get_conda_prefix() -> str:
    """Get conda prefix from environment or sys.prefix."""
    return os.environ.get("CONDA_PREFIX") or sys.prefix


def get_conda_env_for_package() -> str:
    """Get the conda environment where automoma package is installed.

    Uses sys.prefix which correctly identifies the Python's conda environment.
    """
    # sys.prefix is set to the conda environment's prefix when Python is activated
    # For editable installs, automoma.__file__ points to the source, so we can't
    # use that. But sys.prefix correctly identifies the env.
    return sys.prefix


def get_conda_hooks_dir() -> Path:
    """Get the conda activation hooks directory for current env."""
    conda_prefix = get_conda_prefix()
    return Path(conda_prefix) / "etc" / "conda" / "activate.d"


def install_conda_hooks() -> None:
    """Install conda activation hooks to auto-set environment variables.

    This should be run once after installing the package in a conda environment:
        python -m automoma.env install-hooks

    Or via the CLI:
        automoma install-hooks
    """
    import glob

    # Find the conda env where automoma is installed
    conda_env = get_conda_env_for_package()
    print(f"[automoma] Detected conda env: {conda_env}")

    # Find IsaacLab path (search upward from this file)
    # automoma/env.py -> automoma/ -> project root -> third_party/IsaacLab-Arena/submodules/IsaacLab
    this_file = Path(__file__).resolve()
    project_root = this_file.parent.parent  # automoma/ -> project root
    isaaclab_path = project_root / "third_party" / "IsaacLab-Arena" / "submodules" / "IsaacLab"
    isaac_sim_path = os.environ.get(
        "IsaacSim_ROOT",
        "/home/xinhai/isaac-sim-5.1.0"  # default fallback
    )

    # Also search for Isaac Sim at common locations if default doesn't exist
    if not Path(isaac_sim_path).exists():
        possible_paths = [
            Path.home() / "isaac-sim-5.1.0",
            Path("/opt/isaac-sim-5.1.0"),
            Path("/usr/local/isaac-sim-5.1.0"),
        ]
        for p in possible_paths:
            if p.exists():
                isaac_sim_path = str(p)
                break

    hooks_dir = Path(conda_env) / "etc" / "conda" / "activate.d"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    activate_script = hooks_dir / "automoma_env_vars.sh"
    deactivate_script = hooks_dir.parent / "deactivate.d" / "automoma_env_vars.sh"
    deactivate_script.parent.mkdir(parents=True, exist_ok=True)

    # Write activate script
    activate_content = f'''#!/bin/bash
# Auto-generated by automoma.env.install_conda_hooks()
# Sets up environment variables for AutoMoMa sim/train/dev modes

export ISAACLAB_PATH="{isaaclab_path}"
export IsaacSim_ROOT="{isaac_sim_path}"
export AUTOMOMA_OBJECT_ROOT="{project_root}/assets/object"
export AUTOMOMA_SCENE_ROOT="{project_root}/assets/scene/infinigen/kitchen_1130"
export AUTOMOMA_ROBOT_ROOT="{project_root}/assets/robot"

# Source Isaac Sim environment
if [ -f "${{ISAACLAB_PATH}}/_isaac_sim/setup_conda_env.sh" ]; then
    _orig_dir="$(pwd)"
    cd "${{ISAACLAB_PATH}}/_isaac_sim"
    source "./setup_conda_env.sh"
    cd "${{_orig_dir}}"
    unset _orig_dir
fi

export ACCEPT_EULA=Y
export PRIVACY_CONSENT=Y
'''

    deactivate_content = '''#!/bin/bash
# Auto-generated by automoma.env.install_conda_hooks()
# Cleans up environment variables on conda deactivate

unset ISAACLAB_PATH
unset IsaacSim_ROOT
unset AUTOMOMA_OBJECT_ROOT
unset AUTOMOMA_SCENE_ROOT
unset AUTOMOMA_ROBOT_ROOT
unset ACCEPT_EULA
unset PRIVACY_CONSENT
'''

    with open(activate_script, "w") as f:
        f.write(activate_content)
    os.chmod(activate_script, 0o755)

    with open(deactivate_script, "w") as f:
        f.write(deactivate_content)
    os.chmod(deactivate_script, 0o755)

    print(f"[automoma] Installed conda hooks to: {hooks_dir.parent}")
    print(f"  Activate: {activate_script.name}")
    print(f"  Deactivate: {deactivate_script.name}")
    print()
    print("To apply, run:")
    print("  conda deactivate")
    print("  conda activate <env_name>")


def uninstall_conda_hooks() -> None:
    """Remove conda activation hooks."""
    hooks_dir = get_conda_hooks_dir()
    activate_script = hooks_dir / "automoma_env_vars.sh"
    deactivate_script = hooks_dir.parent.parent / "deactivate.d" / "automoma_env_vars.sh"

    removed = []
    for f in [activate_script, deactivate_script]:
        if f.exists():
            f.unlink()
            removed.append(str(f))

    if removed:
        print("[automoma] Removed conda hooks:")
        for f in removed:
            print(f"  {f}")
    else:
        print("[automoma] No conda hooks found to remove.")


def check_environment() -> dict:
    """Check if environment is properly set up for each mode.

    Returns a dict with status for each mode.
    """
    status = {
        "plan": {"ok": False, "issues": []},
        "sim": {"ok": False, "issues": []},
        "train": {"ok": False, "issues": []},
    }

    # Check plan mode
    try:
        import torch

        if torch.cuda.is_available():
            status["plan"]["ok"] = True
        else:
            status["plan"]["issues"].append("CUDA not available")
    except ImportError as e:
        status["plan"]["issues"].append(f"torch not installed: {e}")

    try:
        import curobo

        status["plan"]["ok"] = True
    except ImportError as e:
        status["plan"]["issues"].append(f"curobo not installed: {e}")

    # Check sim mode
    try:
        import carb

        status["sim"]["ok"] = True
    except ImportError as e:
        status["sim"]["issues"].append(f"carb/Isaac Sim not available: {e}")

    # Check train mode
    try:
        import lerobot

        status["train"]["ok"] = True
        status["train"]["version"] = getattr(lerobot, "__version__", "unknown")
    except ImportError as e:
        status["train"]["issues"].append(f"lerobot not installed: {e}")

    # Check environment variables
    if not os.environ.get("ISAACLAB_PATH"):
        status["sim"]["issues"].append("ISAACLAB_PATH not set (run: automoma install-hooks)")

    return status


def main():
    """CLI entry point for environment management."""
    import argparse

    parser = argparse.ArgumentParser(description="AutoMoMa environment management")
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # install-hooks command
    install_parser = subparsers.add_parser("install-hooks", help="Install conda activation hooks")
    install_parser.add_argument(
        "--isaac-sim-root",
        default=None,
        help="Path to Isaac Sim installation (default: auto-detect or /home/xinhai/isaac-sim-5.1.0)"
    )

    # uninstall-hooks command
    subparsers.add_parser("uninstall-hooks", help="Remove conda activation hooks")

    # check command
    check_parser = subparsers.add_parser("check", help="Check environment status")

    args = parser.parse_args()

    if args.command == "install-hooks":
        if args.isaac_sim_root:
            os.environ["IsaacSim_ROOT"] = args.isaac_sim_root
        install_conda_hooks()
    elif args.command == "uninstall-hooks":
        uninstall_conda_hooks()
    elif args.command == "check":
        status = check_environment()
        print("[automoma] Environment Check")
        print("=" * 50)
        for mode, info in status.items():
            ok = info["ok"]
            print(f"  {mode.upper()}: {'OK' if ok else 'NOT READY'}")
            if info.get("issues"):
                for issue in info["issues"]:
                    print(f"    - {issue}")
            if info.get("version"):
                print(f"    Version: {info['version']}")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
